services:
  - type: web
    name: protect-pdf-backend
    env: python
    region: oregon
    buildCommand: pip install -r requirements.txt
    startCommand: bash start.sh
    plan: free
    envVars:
      - key: PYTHON_VERSION
        value: 3.10
